spring:
  application:
    name: KafkaPocMaven
  cloud:
    stream:
      bindings:

        Topic-MicrosoftTenantEvent:
          destination: TOPIC.MICROSOFT.TENANT.EVENT

        Topic-CspTokenEvent:
          destination: TOPIC.CSP.TOKEN.EVENT
