spring:
  application:
    name: KafkaPocMaven
  cloud:
    stream:
      bindings:

        kafkaPocMavenTopicMicrosoftTenantEvent:
          destination: KAFKA.POC.MAVEN.TOPIC.MICROSOFT.TENANT.EVENT

        kafkaPocMavenTopicCspTokenEvent:
          destination: KAFKA.POC.MAVEN.TOPIC.CSP.TOKEN.EVENT
