/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.appdirect.kafkapocmaven.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CspTokenEventType {
  CREATED, UPDATED, EXPIRING, EXPIRED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CspTokenEventType\",\"namespace\":\"com.appdirect.kafkapocmaven.model\",\"symbols\":[\"CREATED\",\"UPDATED\",\"EXPIRING\",\"EXPIRED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
