/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ajayaujlawork.kafkapocmaven.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MicrosoftTenantEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8259991170113830136L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MicrosoftTenantEvent\",\"namespace\":\"com.ajayaujlawork.kafkapocmaven.model\",\"fields\":[{\"name\":\"user_id\",\"type\":\"string\"},{\"name\":\"sales_agent_user_id\",\"type\":\"string\"},{\"name\":\"partner\",\"type\":\"string\"},{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"event_type\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"MicrosoftTenantEventType\",\"symbols\":[\"CREATED\"]}]},{\"name\":\"company_id\",\"type\":\"string\"},{\"name\":\"external_company_id\",\"type\":\"string\"},{\"name\":\"batch_id\",\"type\":\"string\"},{\"name\":\"customer_id\",\"type\":\"string\"},{\"name\":\"sales_agent_customer_id\",\"type\":\"string\"},{\"name\":\"tenant_domain\",\"type\":\"string\"},{\"name\":\"creation_date_time\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"marketplace_order_number\",\"type\":\"int\"},{\"name\":\"tenant_admin_email\",\"type\":\"string\"},{\"name\":\"purchaser_name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MicrosoftTenantEvent> ENCODER =
      new BinaryMessageEncoder<MicrosoftTenantEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MicrosoftTenantEvent> DECODER =
      new BinaryMessageDecoder<MicrosoftTenantEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MicrosoftTenantEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MicrosoftTenantEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MicrosoftTenantEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MicrosoftTenantEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MicrosoftTenantEvent from a ByteBuffer. */
  public static MicrosoftTenantEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence user_id;
  @Deprecated public java.lang.CharSequence sales_agent_user_id;
  @Deprecated public java.lang.CharSequence partner;
  @Deprecated public java.lang.CharSequence sku;
  @Deprecated public MicrosoftTenantEventType event_type;
  @Deprecated public java.lang.CharSequence company_id;
  @Deprecated public java.lang.CharSequence external_company_id;
  @Deprecated public java.lang.CharSequence batch_id;
  @Deprecated public java.lang.CharSequence customer_id;
  @Deprecated public java.lang.CharSequence sales_agent_customer_id;
  @Deprecated public java.lang.CharSequence tenant_domain;
  @Deprecated public long creation_date_time;
  @Deprecated public int marketplace_order_number;
  @Deprecated public java.lang.CharSequence tenant_admin_email;
  @Deprecated public java.lang.CharSequence purchaser_name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MicrosoftTenantEvent() {}

  /**
   * All-args constructor.
   * @param user_id The new value for user_id
   * @param sales_agent_user_id The new value for sales_agent_user_id
   * @param partner The new value for partner
   * @param sku The new value for sku
   * @param event_type The new value for event_type
   * @param company_id The new value for company_id
   * @param external_company_id The new value for external_company_id
   * @param batch_id The new value for batch_id
   * @param customer_id The new value for customer_id
   * @param sales_agent_customer_id The new value for sales_agent_customer_id
   * @param tenant_domain The new value for tenant_domain
   * @param creation_date_time The new value for creation_date_time
   * @param marketplace_order_number The new value for marketplace_order_number
   * @param tenant_admin_email The new value for tenant_admin_email
   * @param purchaser_name The new value for purchaser_name
   */
  public MicrosoftTenantEvent(java.lang.CharSequence user_id, java.lang.CharSequence sales_agent_user_id, java.lang.CharSequence partner, java.lang.CharSequence sku, MicrosoftTenantEventType event_type, java.lang.CharSequence company_id, java.lang.CharSequence external_company_id, java.lang.CharSequence batch_id, java.lang.CharSequence customer_id, java.lang.CharSequence sales_agent_customer_id, java.lang.CharSequence tenant_domain, java.lang.Long creation_date_time, java.lang.Integer marketplace_order_number, java.lang.CharSequence tenant_admin_email, java.lang.CharSequence purchaser_name) {
    this.user_id = user_id;
    this.sales_agent_user_id = sales_agent_user_id;
    this.partner = partner;
    this.sku = sku;
    this.event_type = event_type;
    this.company_id = company_id;
    this.external_company_id = external_company_id;
    this.batch_id = batch_id;
    this.customer_id = customer_id;
    this.sales_agent_customer_id = sales_agent_customer_id;
    this.tenant_domain = tenant_domain;
    this.creation_date_time = creation_date_time;
    this.marketplace_order_number = marketplace_order_number;
    this.tenant_admin_email = tenant_admin_email;
    this.purchaser_name = purchaser_name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_id;
    case 1: return sales_agent_user_id;
    case 2: return partner;
    case 3: return sku;
    case 4: return event_type;
    case 5: return company_id;
    case 6: return external_company_id;
    case 7: return batch_id;
    case 8: return customer_id;
    case 9: return sales_agent_customer_id;
    case 10: return tenant_domain;
    case 11: return creation_date_time;
    case 12: return marketplace_order_number;
    case 13: return tenant_admin_email;
    case 14: return purchaser_name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_id = (java.lang.CharSequence)value$; break;
    case 1: sales_agent_user_id = (java.lang.CharSequence)value$; break;
    case 2: partner = (java.lang.CharSequence)value$; break;
    case 3: sku = (java.lang.CharSequence)value$; break;
    case 4: event_type = (MicrosoftTenantEventType)value$; break;
    case 5: company_id = (java.lang.CharSequence)value$; break;
    case 6: external_company_id = (java.lang.CharSequence)value$; break;
    case 7: batch_id = (java.lang.CharSequence)value$; break;
    case 8: customer_id = (java.lang.CharSequence)value$; break;
    case 9: sales_agent_customer_id = (java.lang.CharSequence)value$; break;
    case 10: tenant_domain = (java.lang.CharSequence)value$; break;
    case 11: creation_date_time = (java.lang.Long)value$; break;
    case 12: marketplace_order_number = (java.lang.Integer)value$; break;
    case 13: tenant_admin_email = (java.lang.CharSequence)value$; break;
    case 14: purchaser_name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.CharSequence getUserId() {
    return user_id;
  }

  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'sales_agent_user_id' field.
   * @return The value of the 'sales_agent_user_id' field.
   */
  public java.lang.CharSequence getSalesAgentUserId() {
    return sales_agent_user_id;
  }

  /**
   * Sets the value of the 'sales_agent_user_id' field.
   * @param value the value to set.
   */
  public void setSalesAgentUserId(java.lang.CharSequence value) {
    this.sales_agent_user_id = value;
  }

  /**
   * Gets the value of the 'partner' field.
   * @return The value of the 'partner' field.
   */
  public java.lang.CharSequence getPartner() {
    return partner;
  }

  /**
   * Sets the value of the 'partner' field.
   * @param value the value to set.
   */
  public void setPartner(java.lang.CharSequence value) {
    this.partner = value;
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public java.lang.CharSequence getSku() {
    return sku;
  }

  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(java.lang.CharSequence value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'event_type' field.
   * @return The value of the 'event_type' field.
   */
  public MicrosoftTenantEventType getEventType() {
    return event_type;
  }

  /**
   * Sets the value of the 'event_type' field.
   * @param value the value to set.
   */
  public void setEventType(MicrosoftTenantEventType value) {
    this.event_type = value;
  }

  /**
   * Gets the value of the 'company_id' field.
   * @return The value of the 'company_id' field.
   */
  public java.lang.CharSequence getCompanyId() {
    return company_id;
  }

  /**
   * Sets the value of the 'company_id' field.
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.CharSequence value) {
    this.company_id = value;
  }

  /**
   * Gets the value of the 'external_company_id' field.
   * @return The value of the 'external_company_id' field.
   */
  public java.lang.CharSequence getExternalCompanyId() {
    return external_company_id;
  }

  /**
   * Sets the value of the 'external_company_id' field.
   * @param value the value to set.
   */
  public void setExternalCompanyId(java.lang.CharSequence value) {
    this.external_company_id = value;
  }

  /**
   * Gets the value of the 'batch_id' field.
   * @return The value of the 'batch_id' field.
   */
  public java.lang.CharSequence getBatchId() {
    return batch_id;
  }

  /**
   * Sets the value of the 'batch_id' field.
   * @param value the value to set.
   */
  public void setBatchId(java.lang.CharSequence value) {
    this.batch_id = value;
  }

  /**
   * Gets the value of the 'customer_id' field.
   * @return The value of the 'customer_id' field.
   */
  public java.lang.CharSequence getCustomerId() {
    return customer_id;
  }

  /**
   * Sets the value of the 'customer_id' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customer_id = value;
  }

  /**
   * Gets the value of the 'sales_agent_customer_id' field.
   * @return The value of the 'sales_agent_customer_id' field.
   */
  public java.lang.CharSequence getSalesAgentCustomerId() {
    return sales_agent_customer_id;
  }

  /**
   * Sets the value of the 'sales_agent_customer_id' field.
   * @param value the value to set.
   */
  public void setSalesAgentCustomerId(java.lang.CharSequence value) {
    this.sales_agent_customer_id = value;
  }

  /**
   * Gets the value of the 'tenant_domain' field.
   * @return The value of the 'tenant_domain' field.
   */
  public java.lang.CharSequence getTenantDomain() {
    return tenant_domain;
  }

  /**
   * Sets the value of the 'tenant_domain' field.
   * @param value the value to set.
   */
  public void setTenantDomain(java.lang.CharSequence value) {
    this.tenant_domain = value;
  }

  /**
   * Gets the value of the 'creation_date_time' field.
   * @return The value of the 'creation_date_time' field.
   */
  public java.lang.Long getCreationDateTime() {
    return creation_date_time;
  }

  /**
   * Sets the value of the 'creation_date_time' field.
   * @param value the value to set.
   */
  public void setCreationDateTime(java.lang.Long value) {
    this.creation_date_time = value;
  }

  /**
   * Gets the value of the 'marketplace_order_number' field.
   * @return The value of the 'marketplace_order_number' field.
   */
  public java.lang.Integer getMarketplaceOrderNumber() {
    return marketplace_order_number;
  }

  /**
   * Sets the value of the 'marketplace_order_number' field.
   * @param value the value to set.
   */
  public void setMarketplaceOrderNumber(java.lang.Integer value) {
    this.marketplace_order_number = value;
  }

  /**
   * Gets the value of the 'tenant_admin_email' field.
   * @return The value of the 'tenant_admin_email' field.
   */
  public java.lang.CharSequence getTenantAdminEmail() {
    return tenant_admin_email;
  }

  /**
   * Sets the value of the 'tenant_admin_email' field.
   * @param value the value to set.
   */
  public void setTenantAdminEmail(java.lang.CharSequence value) {
    this.tenant_admin_email = value;
  }

  /**
   * Gets the value of the 'purchaser_name' field.
   * @return The value of the 'purchaser_name' field.
   */
  public java.lang.CharSequence getPurchaserName() {
    return purchaser_name;
  }

  /**
   * Sets the value of the 'purchaser_name' field.
   * @param value the value to set.
   */
  public void setPurchaserName(java.lang.CharSequence value) {
    this.purchaser_name = value;
  }

  /**
   * Creates a new MicrosoftTenantEvent RecordBuilder.
   * @return A new MicrosoftTenantEvent RecordBuilder
   */
  public static MicrosoftTenantEvent.Builder newBuilder() {
    return new MicrosoftTenantEvent.Builder();
  }

  /**
   * Creates a new MicrosoftTenantEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MicrosoftTenantEvent RecordBuilder
   */
  public static MicrosoftTenantEvent.Builder newBuilder(MicrosoftTenantEvent.Builder other) {
    return new MicrosoftTenantEvent.Builder(other);
  }

  /**
   * Creates a new MicrosoftTenantEvent RecordBuilder by copying an existing MicrosoftTenantEvent instance.
   * @param other The existing instance to copy.
   * @return A new MicrosoftTenantEvent RecordBuilder
   */
  public static MicrosoftTenantEvent.Builder newBuilder(MicrosoftTenantEvent other) {
    return new MicrosoftTenantEvent.Builder(other);
  }

  /**
   * RecordBuilder for MicrosoftTenantEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MicrosoftTenantEvent>
    implements org.apache.avro.data.RecordBuilder<MicrosoftTenantEvent> {

    private java.lang.CharSequence user_id;
    private java.lang.CharSequence sales_agent_user_id;
    private java.lang.CharSequence partner;
    private java.lang.CharSequence sku;
    private MicrosoftTenantEventType event_type;
    private java.lang.CharSequence company_id;
    private java.lang.CharSequence external_company_id;
    private java.lang.CharSequence batch_id;
    private java.lang.CharSequence customer_id;
    private java.lang.CharSequence sales_agent_customer_id;
    private java.lang.CharSequence tenant_domain;
    private long creation_date_time;
    private int marketplace_order_number;
    private java.lang.CharSequence tenant_admin_email;
    private java.lang.CharSequence purchaser_name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(MicrosoftTenantEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sales_agent_user_id)) {
        this.sales_agent_user_id = data().deepCopy(fields()[1].schema(), other.sales_agent_user_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.partner)) {
        this.partner = data().deepCopy(fields()[2].schema(), other.partner);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sku)) {
        this.sku = data().deepCopy(fields()[3].schema(), other.sku);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.event_type)) {
        this.event_type = data().deepCopy(fields()[4].schema(), other.event_type);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.company_id)) {
        this.company_id = data().deepCopy(fields()[5].schema(), other.company_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.external_company_id)) {
        this.external_company_id = data().deepCopy(fields()[6].schema(), other.external_company_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.batch_id)) {
        this.batch_id = data().deepCopy(fields()[7].schema(), other.batch_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[8].schema(), other.customer_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.sales_agent_customer_id)) {
        this.sales_agent_customer_id = data().deepCopy(fields()[9].schema(), other.sales_agent_customer_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tenant_domain)) {
        this.tenant_domain = data().deepCopy(fields()[10].schema(), other.tenant_domain);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.creation_date_time)) {
        this.creation_date_time = data().deepCopy(fields()[11].schema(), other.creation_date_time);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.marketplace_order_number)) {
        this.marketplace_order_number = data().deepCopy(fields()[12].schema(), other.marketplace_order_number);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.tenant_admin_email)) {
        this.tenant_admin_email = data().deepCopy(fields()[13].schema(), other.tenant_admin_email);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.purchaser_name)) {
        this.purchaser_name = data().deepCopy(fields()[14].schema(), other.purchaser_name);
        fieldSetFlags()[14] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MicrosoftTenantEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(MicrosoftTenantEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sales_agent_user_id)) {
        this.sales_agent_user_id = data().deepCopy(fields()[1].schema(), other.sales_agent_user_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.partner)) {
        this.partner = data().deepCopy(fields()[2].schema(), other.partner);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sku)) {
        this.sku = data().deepCopy(fields()[3].schema(), other.sku);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.event_type)) {
        this.event_type = data().deepCopy(fields()[4].schema(), other.event_type);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.company_id)) {
        this.company_id = data().deepCopy(fields()[5].schema(), other.company_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.external_company_id)) {
        this.external_company_id = data().deepCopy(fields()[6].schema(), other.external_company_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.batch_id)) {
        this.batch_id = data().deepCopy(fields()[7].schema(), other.batch_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[8].schema(), other.customer_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.sales_agent_customer_id)) {
        this.sales_agent_customer_id = data().deepCopy(fields()[9].schema(), other.sales_agent_customer_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tenant_domain)) {
        this.tenant_domain = data().deepCopy(fields()[10].schema(), other.tenant_domain);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.creation_date_time)) {
        this.creation_date_time = data().deepCopy(fields()[11].schema(), other.creation_date_time);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.marketplace_order_number)) {
        this.marketplace_order_number = data().deepCopy(fields()[12].schema(), other.marketplace_order_number);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.tenant_admin_email)) {
        this.tenant_admin_email = data().deepCopy(fields()[13].schema(), other.tenant_admin_email);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.purchaser_name)) {
        this.purchaser_name = data().deepCopy(fields()[14].schema(), other.purchaser_name);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return user_id;
    }

    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.user_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sales_agent_user_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getSalesAgentUserId() {
      return sales_agent_user_id;
    }

    /**
      * Sets the value of the 'sales_agent_user_id' field.
      * @param value The value of 'sales_agent_user_id'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setSalesAgentUserId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sales_agent_user_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sales_agent_user_id' field has been set.
      * @return True if the 'sales_agent_user_id' field has been set, false otherwise.
      */
    public boolean hasSalesAgentUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sales_agent_user_id' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearSalesAgentUserId() {
      sales_agent_user_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'partner' field.
      * @return The value.
      */
    public java.lang.CharSequence getPartner() {
      return partner;
    }

    /**
      * Sets the value of the 'partner' field.
      * @param value The value of 'partner'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setPartner(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.partner = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'partner' field has been set.
      * @return True if the 'partner' field has been set, false otherwise.
      */
    public boolean hasPartner() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'partner' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearPartner() {
      partner = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public java.lang.CharSequence getSku() {
      return sku;
    }

    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setSku(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.sku = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearSku() {
      sku = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'event_type' field.
      * @return The value.
      */
    public MicrosoftTenantEventType getEventType() {
      return event_type;
    }

    /**
      * Sets the value of the 'event_type' field.
      * @param value The value of 'event_type'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setEventType(MicrosoftTenantEventType value) {
      validate(fields()[4], value);
      this.event_type = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'event_type' field has been set.
      * @return True if the 'event_type' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'event_type' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearEventType() {
      event_type = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'company_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyId() {
      return company_id;
    }

    /**
      * Sets the value of the 'company_id' field.
      * @param value The value of 'company_id'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setCompanyId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.company_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'company_id' field has been set.
      * @return True if the 'company_id' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'company_id' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearCompanyId() {
      company_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'external_company_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getExternalCompanyId() {
      return external_company_id;
    }

    /**
      * Sets the value of the 'external_company_id' field.
      * @param value The value of 'external_company_id'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setExternalCompanyId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.external_company_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'external_company_id' field has been set.
      * @return True if the 'external_company_id' field has been set, false otherwise.
      */
    public boolean hasExternalCompanyId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'external_company_id' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearExternalCompanyId() {
      external_company_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'batch_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getBatchId() {
      return batch_id;
    }

    /**
      * Sets the value of the 'batch_id' field.
      * @param value The value of 'batch_id'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setBatchId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.batch_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'batch_id' field has been set.
      * @return True if the 'batch_id' field has been set, false otherwise.
      */
    public boolean hasBatchId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'batch_id' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearBatchId() {
      batch_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customer_id;
    }

    /**
      * Sets the value of the 'customer_id' field.
      * @param value The value of 'customer_id'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.customer_id = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_id' field has been set.
      * @return True if the 'customer_id' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'customer_id' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearCustomerId() {
      customer_id = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'sales_agent_customer_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getSalesAgentCustomerId() {
      return sales_agent_customer_id;
    }

    /**
      * Sets the value of the 'sales_agent_customer_id' field.
      * @param value The value of 'sales_agent_customer_id'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setSalesAgentCustomerId(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.sales_agent_customer_id = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'sales_agent_customer_id' field has been set.
      * @return True if the 'sales_agent_customer_id' field has been set, false otherwise.
      */
    public boolean hasSalesAgentCustomerId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'sales_agent_customer_id' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearSalesAgentCustomerId() {
      sales_agent_customer_id = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'tenant_domain' field.
      * @return The value.
      */
    public java.lang.CharSequence getTenantDomain() {
      return tenant_domain;
    }

    /**
      * Sets the value of the 'tenant_domain' field.
      * @param value The value of 'tenant_domain'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setTenantDomain(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.tenant_domain = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'tenant_domain' field has been set.
      * @return True if the 'tenant_domain' field has been set, false otherwise.
      */
    public boolean hasTenantDomain() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'tenant_domain' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearTenantDomain() {
      tenant_domain = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'creation_date_time' field.
      * @return The value.
      */
    public java.lang.Long getCreationDateTime() {
      return creation_date_time;
    }

    /**
      * Sets the value of the 'creation_date_time' field.
      * @param value The value of 'creation_date_time'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setCreationDateTime(long value) {
      validate(fields()[11], value);
      this.creation_date_time = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'creation_date_time' field has been set.
      * @return True if the 'creation_date_time' field has been set, false otherwise.
      */
    public boolean hasCreationDateTime() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'creation_date_time' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearCreationDateTime() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'marketplace_order_number' field.
      * @return The value.
      */
    public java.lang.Integer getMarketplaceOrderNumber() {
      return marketplace_order_number;
    }

    /**
      * Sets the value of the 'marketplace_order_number' field.
      * @param value The value of 'marketplace_order_number'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setMarketplaceOrderNumber(int value) {
      validate(fields()[12], value);
      this.marketplace_order_number = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'marketplace_order_number' field has been set.
      * @return True if the 'marketplace_order_number' field has been set, false otherwise.
      */
    public boolean hasMarketplaceOrderNumber() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'marketplace_order_number' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearMarketplaceOrderNumber() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'tenant_admin_email' field.
      * @return The value.
      */
    public java.lang.CharSequence getTenantAdminEmail() {
      return tenant_admin_email;
    }

    /**
      * Sets the value of the 'tenant_admin_email' field.
      * @param value The value of 'tenant_admin_email'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setTenantAdminEmail(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.tenant_admin_email = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'tenant_admin_email' field has been set.
      * @return True if the 'tenant_admin_email' field has been set, false otherwise.
      */
    public boolean hasTenantAdminEmail() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'tenant_admin_email' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearTenantAdminEmail() {
      tenant_admin_email = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'purchaser_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getPurchaserName() {
      return purchaser_name;
    }

    /**
      * Sets the value of the 'purchaser_name' field.
      * @param value The value of 'purchaser_name'.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder setPurchaserName(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.purchaser_name = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'purchaser_name' field has been set.
      * @return True if the 'purchaser_name' field has been set, false otherwise.
      */
    public boolean hasPurchaserName() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'purchaser_name' field.
      * @return This builder.
      */
    public MicrosoftTenantEvent.Builder clearPurchaserName() {
      purchaser_name = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MicrosoftTenantEvent build() {
      try {
        MicrosoftTenantEvent record = new MicrosoftTenantEvent();
        record.user_id = fieldSetFlags()[0] ? this.user_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sales_agent_user_id = fieldSetFlags()[1] ? this.sales_agent_user_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.partner = fieldSetFlags()[2] ? this.partner : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sku = fieldSetFlags()[3] ? this.sku : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.event_type = fieldSetFlags()[4] ? this.event_type : (MicrosoftTenantEventType) defaultValue(fields()[4]);
        record.company_id = fieldSetFlags()[5] ? this.company_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.external_company_id = fieldSetFlags()[6] ? this.external_company_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.batch_id = fieldSetFlags()[7] ? this.batch_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.customer_id = fieldSetFlags()[8] ? this.customer_id : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.sales_agent_customer_id = fieldSetFlags()[9] ? this.sales_agent_customer_id : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.tenant_domain = fieldSetFlags()[10] ? this.tenant_domain : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.creation_date_time = fieldSetFlags()[11] ? this.creation_date_time : (java.lang.Long) defaultValue(fields()[11]);
        record.marketplace_order_number = fieldSetFlags()[12] ? this.marketplace_order_number : (java.lang.Integer) defaultValue(fields()[12]);
        record.tenant_admin_email = fieldSetFlags()[13] ? this.tenant_admin_email : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.purchaser_name = fieldSetFlags()[14] ? this.purchaser_name : (java.lang.CharSequence) defaultValue(fields()[14]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MicrosoftTenantEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<MicrosoftTenantEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MicrosoftTenantEvent>
    READER$ = (org.apache.avro.io.DatumReader<MicrosoftTenantEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
